export const AI_PROBE_MANIFEST = [
  {
    id: 'SMOKE_CHAT_BASIC',
    specPath: 'e2e/smoke/chat-basic.spec.ts',
    kind: 'smoke',
    mode: 'live',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['SMOKE'],
    expectedSignals: ['assistant-response', 'reader-chat-flow'],
  },
  {
    id: 'B6_SIMPLE_TOOL_SELECTION',
    specPath: 'e2e/probes/b6-tool-selection-simple.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['B6'],
    expectedSignals: ['tool-selection', 'grounded-answer'],
  },
  {
    id: 'B6_TOOL_SELECTION',
    specPath: 'e2e/probes/b6-tool-selection.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['B6'],
    expectedSignals: ['tool-selection', 'multi-query'],
  },
  {
    id: 'C11_SPOILER_PROTECTION',
    specPath: 'e2e/probes/c11-spoiler-protection.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'high',
    status: 'active',
    featureIds: ['C11'],
    expectedSignals: ['spoiler-protection'],
  },
  {
    id: 'E22_TOOL_STATUS_UI',
    specPath: 'e2e/probes/e22-tool-status-ui.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['E22'],
    expectedSignals: ['tool-status-ui'],
  },
  {
    id: 'F25_RATE_LIMIT_UX',
    specPath: 'e2e/probes/f25-rate-limit-ux.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['F25'],
    expectedSignals: ['rate-limit-ux'],
  },
  {
    id: 'F26_TOOL_FAILURES',
    specPath: 'e2e/probes/f26-tool-failures.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'high',
    status: 'active',
    featureIds: ['F26'],
    expectedSignals: ['tool-failure-recovery'],
  },
  {
    id: 'F27_ERROR_PATHS',
    specPath: 'e2e/probes/f27-error-paths.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['F27'],
    expectedSignals: ['error-rendering'],
  },
  {
    id: 'F28_CANCEL_MIDSTREAM',
    specPath: 'e2e/probes/f28-cancel-midstream.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['F28'],
    expectedSignals: ['cancel', 'composer-unlock'],
  },
  {
    id: 'G31_MESSAGE_PERSISTENCE',
    specPath: 'e2e/probes/g31-message-persistence.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['G31'],
    expectedSignals: ['persistence'],
  },
  {
    id: 'G32_ORPHAN_CONVERSATIONS',
    specPath: 'e2e/probes/g32-orphan-conversations.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['G32'],
    expectedSignals: ['conversation-integrity'],
  },
  {
    id: 'H35_MODEL_ROUTING',
    specPath: 'e2e/probes/h35-model-routing.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['H35'],
    expectedSignals: ['model-routing', 'observability-headers'],
  },
  {
    id: 'I40_LATENCY_TTFT',
    specPath: 'e2e/probes/i40-latency-ttft.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['I40'],
    expectedSignals: ['latency', 'ttft'],
  },
  {
    id: 'A3_SUGGESTION_CHIPS',
    specPath: 'e2e/probes/a3-suggestion-chips.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['A3'],
    expectedSignals: ['suggestions'],
  },
  {
    id: 'A4_INPUT_EDGE_CASES',
    specPath: 'e2e/probes/a4-input-edge-cases.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['A4'],
    expectedSignals: ['input-validation'],
  },
  {
    id: 'B7_BRANCH_REGENERATION',
    specPath: 'e2e/probes/b7-branch-regeneration.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['B7'],
    expectedSignals: ['regenerate', 'branch-picker'],
  },
  {
    id: 'B8_STEP_COUNT_LIMIT',
    specPath: 'e2e/probes/b8-step-count-limit.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'critical',
    priority: 'high',
    status: 'active',
    featureIds: ['B8'],
    expectedSignals: ['step-limit', 'fallback'],
  },
  {
    id: 'C12_LINKIFY_QUOTES',
    specPath: 'e2e/probes/c12-linkify-quotes.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['C12'],
    expectedSignals: ['citations'],
  },
  {
    id: 'Q01_CROSS_TAB_QUOTA',
    specPath: 'e2e/probes/q01-cross-tab-quota.spec.ts',
    kind: 'probe',
    mode: 'live',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['Q01'],
    expectedSignals: ['quota-sync'],
  },
  {
    id: 'Q02_QUOTA_WARNING',
    specPath: 'e2e/probes/q02-quota-warning.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['Q02'],
    expectedSignals: ['quota-warning'],
  },
  {
    id: 'S01_XSS_RESPONSE_CLEANER',
    specPath: 'e2e/probes/s01-xss-response-cleaner.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'high',
    status: 'active',
    featureIds: ['S01'],
    expectedSignals: ['sanitization'],
  },
  {
    id: 'ENH_A13_COMPACTION',
    specPath: 'e2e/probes/enh-a13-compaction.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'deferred',
    featureIds: ['A13'],
    expectedSignals: ['compaction'],
    blockedBy:
      'Conversation compaction runtime is deferred; keep this as evidence, not an active gate.',
  },
  {
    id: 'ENH_A17_STREAMING_DELTAS',
    specPath: 'e2e/probes/enh-a17-streaming-deltas.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['A17'],
    expectedSignals: ['text-delta'],
  },
  {
    id: 'ENH_C1_OBSERVABILITY',
    specPath: 'e2e/probes/enh-c1-observability.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'active',
    featureIds: ['C1'],
    expectedSignals: ['no-client-debug-leak'],
  },
  {
    id: 'ENH2_ADAPTIVE_STEP_BUDGET',
    specPath: 'e2e/probes/enh2-adaptive-step-budget.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'deferred',
    featureIds: ['ENH2'],
    expectedSignals: ['internal-step-policy'],
    blockedBy:
      'Adaptive step policy must remain server-side; no client-visible telemetry contract is approved.',
  },
  {
    id: 'ENH8_TOOL_EXECUTION_CONTEXT',
    specPath: 'e2e/probes/enh8-tool-execution-context.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'deferred',
    featureIds: ['ENH8'],
    expectedSignals: ['tool-context'],
    blockedBy:
      'Shared tool execution state is deferred; this mock probe should not be an active gate.',
  },
  {
    id: 'ENH9_RECOVERY_REPLANNING',
    specPath: 'e2e/probes/enh9-recovery-replanning.spec.ts',
    kind: 'probe',
    mode: 'mock',
    batch: 'extended',
    priority: 'medium',
    status: 'deferred',
    featureIds: ['ENH9'],
    expectedSignals: ['replanning'],
    blockedBy:
      'Bonus-step re-planning runtime is deferred; this mock probe should not be an active gate.',
  },
];

export function getProbeBatch(batch = 'critical') {
  const activeProbes = AI_PROBE_MANIFEST.filter((probe) => probe.status === 'active');
  if (batch === 'all') return activeProbes;
  return activeProbes.filter((probe) => probe.batch === batch);
}
