// Bundle D4 — Rust test skeleton.
// See docs/probe-driven-workflow-implementation.md §3 Bundle D.
//
// This module exists primarily to prove `cargo test` is wired for the
// Tauri crate and to host the `generate_bindings` test that CI runs
// to verify `apps/openread-app/src/bindings.ts` is up to date
// (§11 `specta-contract-diff` job).

#[test]
fn works() {
    // Sanity check: if this fails, the toolchain is misconfigured.
    assert_eq!(2 + 2, 4);
}

/// CI entry-point: `cargo test generate_bindings` invoked by the
/// `specta-contract-diff` GitHub Actions job (see §11). It (re)emits
/// `apps/openread-app/src/bindings.ts`; the subsequent
/// `git diff --exit-code` step in CI fails the job when the file is
/// stale.
///
/// TODO(Bundle D1 follow-up): until every `#[tauri::command]` in
/// `lib.rs` is annotated with `#[specta::specta]` and registered in
/// `specta_builder()`, the emitted bindings only cover the sample
/// probe commands. Expanding coverage is the next increment.
#[test]
fn generate_bindings() {
    use specta_typescript::Typescript;

    let builder = crate::specta_builder();

    // The emitted file contains auto-generated `any`s and unused consts
    // (TAURI_CHANNEL, __makeEvents__) that are expected for tauri-specta
    // output. Inject an ESLint + TS disable header so the file doesn't
    // trip the L4 lint/typecheck gates — it's machine-authored and must
    // not be hand-edited anyway. `framework_header` is emitted separately
    // and already includes the "generated by tauri-specta" notice, so we
    // only prepend the lint/ts pragmas here.
    let ts = Typescript::default().header("/* eslint-disable */\n// @ts-nocheck\n");

    // Path is relative to the crate root (`apps/openread-app/src-tauri`).
    // `../src/bindings.ts` resolves to `apps/openread-app/src/bindings.ts`
    // which is the path referenced in §4.1 of the implementation doc.
    builder
        .export(ts, "../src/bindings.ts")
        .expect("failed to export tauri-specta TypeScript bindings");
}
